import{a as v,S as b,i as l}from"./assets/vendor-BkVuWn-o.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();async function m(e,r=1){try{return(await v.get("https://pixabay.com/api/",{params:{key:"53489981-68e2194cff91adb725bcb77ca",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch{throw new Error("Pixabay API error")}}const i={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".js-load-more")};let S=new b(".gallery a",{captionsData:"alt",captionDelay:250});function q({webformatURL:e,largeImageURL:r,tags:a,likes:n,views:t,comments:o,downloads:c}){return`
    <li class = "gallery-item">
        <a href="${r}">
            <img src="${e}" alt="${a}" loading="lazy" width="360" height="200"/>
        </a>
        <div class="card-info">
            <div class="headers"><span>Likes</span><span>Views</span><span>Comments</span><span>Downloads</span></div>
            <div class="values"><span>${n}</span><span>${t}</span><span>${o}</span><span>${c}</span></div>
        </div>
    </li>`}function B(e){return e.map(q).join("")}function y(e){const r=B(e);i.gallery.insertAdjacentHTML("beforeend",r),S.refresh()}function M(){i.gallery.innerHTML=""}function g(){i.loader.classList.remove("hidden")}function L(){i.loader.classList.add("hidden")}function P(){i.loadMoreBtn.classList.remove("hidden")}function f(){i.loadMoreBtn.classList.add("hidden")}function w(e,r){e<r?P():f()}const p={form:document.querySelector(".js-pixabay-form"),input:document.querySelector("input[name='search-text']"),loadMoreBtn:document.querySelector(".js-load-more")},x=15;let d="",s,h=0,u;function $(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}p.form.addEventListener("submit",async e=>{if(e.preventDefault(),d=new FormData(e.target).get("search-text").trim(),!d){l.show({title:"Hey",message:"Please enter a search query!"});return}s=1,M(),f(),g();try{const a=await m(d,s);if(h=a.totalHits,a.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const n=a.hits;y(n),u=Math.ceil(h/x),w(s,u)}catch{l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}finally{L()}p.form.reset()});p.loadMoreBtn.addEventListener("click",async()=>{s+=1,g();try{const e=await m(d,s);y(e.hits),$(),s>=u?(f(),l.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w(s,u)}catch{l.error({message:"Something went wrong!",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
